import "./globals.css";
import {Cormorant_Upright, Open_Sans} from "next/font/google";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";

const cormorantUpright = Cormorant_Upright({
    subsets: ["latin"],
    weight: ['300','400','500', '600', '700'],
    variable: '--font-cormorantUpright'
});
const openSans = Open_Sans({
    subsets: ["latin"],
    weight: ['300','400','500', '600', '700', '800'],
    variable: '--font-openSans'
})
export const metadata = {
    title: 'CoffeeLanding',
    description: 'Generated by create next app',
    icon: '/favicon.ico'
};

export default function RootLayout({ children }) {
    return (
        <html lang= 'en'>
        <body className = {`${cormorantUpright.variable} ${openSans.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
